























.build_ano/pro/TimedAction/TimedAction.o : lib/TimedAction/TimedAction.cpp
	@echo [93mTimedAction/TimedAction.cpp[0m
	@mkdir -p .build_ano/pro/TimedAction
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c lib/TimedAction/TimedAction.cpp
include .build_ano/pro/TimedAction/TimedAction.d



.build_ano/pro/TimedAction/libTimedAction.a : .build_ano/pro/TimedAction/TimedAction.o
	@echo [92mLinking libTimedAction.a[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^












.build_ano/pro/RF22/RF22.o : lib/RF22/RF22.cpp
	@echo [93mRF22/RF22.cpp[0m
	@mkdir -p .build_ano/pro/RF22
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c lib/RF22/RF22.cpp
include .build_ano/pro/RF22/RF22.d

.build_ano/pro/RF22/RF22ReliableDatagram.o : lib/RF22/RF22ReliableDatagram.cpp
	@echo [93mRF22/RF22ReliableDatagram.cpp[0m
	@mkdir -p .build_ano/pro/RF22
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c lib/RF22/RF22ReliableDatagram.cpp
include .build_ano/pro/RF22/RF22ReliableDatagram.d

.build_ano/pro/RF22/HardwareSPI.o : lib/RF22/HardwareSPI.cpp
	@echo [93mRF22/HardwareSPI.cpp[0m
	@mkdir -p .build_ano/pro/RF22
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c lib/RF22/HardwareSPI.cpp
include .build_ano/pro/RF22/HardwareSPI.d

.build_ano/pro/RF22/RF22Datagram.o : lib/RF22/RF22Datagram.cpp
	@echo [93mRF22/RF22Datagram.cpp[0m
	@mkdir -p .build_ano/pro/RF22
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c lib/RF22/RF22Datagram.cpp
include .build_ano/pro/RF22/RF22Datagram.d

.build_ano/pro/RF22/RF22Router.o : lib/RF22/RF22Router.cpp
	@echo [93mRF22/RF22Router.cpp[0m
	@mkdir -p .build_ano/pro/RF22
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c lib/RF22/RF22Router.cpp
include .build_ano/pro/RF22/RF22Router.d

.build_ano/pro/RF22/RF22Mesh.o : lib/RF22/RF22Mesh.cpp
	@echo [93mRF22/RF22Mesh.cpp[0m
	@mkdir -p .build_ano/pro/RF22
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c lib/RF22/RF22Mesh.cpp
include .build_ano/pro/RF22/RF22Mesh.d



.build_ano/pro/RF22/libRF22.a : .build_ano/pro/RF22/RF22.o .build_ano/pro/RF22/RF22ReliableDatagram.o .build_ano/pro/RF22/HardwareSPI.o .build_ano/pro/RF22/RF22Datagram.o .build_ano/pro/RF22/RF22Router.o .build_ano/pro/RF22/RF22Mesh.o
	@echo [92mLinking libRF22.a[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^












.build_ano/pro/SPI/SPI.o : /usr/share/arduino/hardware/arduino/avr/libraries/SPI/SPI.cpp
	@echo [93mSPI/SPI.cpp[0m
	@mkdir -p .build_ano/pro/SPI
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/libraries/SPI/SPI.cpp
include .build_ano/pro/SPI/SPI.d



.build_ano/pro/SPI/libSPI.a : .build_ano/pro/SPI/SPI.o
	@echo [92mLinking libSPI.a[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^







.build_ano/pro/arduino/hooks.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.c
	@echo [93marduino/hooks.c[0m
	@mkdir -p .build_ano/pro/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.c
include .build_ano/pro/arduino/hooks.d

.build_ano/pro/arduino/WInterrupts.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.c
	@echo [93marduino/WInterrupts.c[0m
	@mkdir -p .build_ano/pro/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.c
include .build_ano/pro/arduino/WInterrupts.d

.build_ano/pro/arduino/wiring_shift.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.c
	@echo [93marduino/wiring_shift.c[0m
	@mkdir -p .build_ano/pro/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.c
include .build_ano/pro/arduino/wiring_shift.d

.build_ano/pro/arduino/wiring_pulse.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.c
	@echo [93marduino/wiring_pulse.c[0m
	@mkdir -p .build_ano/pro/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.c
include .build_ano/pro/arduino/wiring_pulse.d

.build_ano/pro/arduino/wiring_analog.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.c
	@echo [93marduino/wiring_analog.c[0m
	@mkdir -p .build_ano/pro/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.c
include .build_ano/pro/arduino/wiring_analog.d

.build_ano/pro/arduino/wiring_digital.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.c
	@echo [93marduino/wiring_digital.c[0m
	@mkdir -p .build_ano/pro/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.c
include .build_ano/pro/arduino/wiring_digital.d

.build_ano/pro/arduino/wiring.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.c
	@echo [93marduino/wiring.c[0m
	@mkdir -p .build_ano/pro/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.c
include .build_ano/pro/arduino/wiring.d






.build_ano/pro/arduino/Print.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.cpp
	@echo [93marduino/Print.cpp[0m
	@mkdir -p .build_ano/pro/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.cpp
include .build_ano/pro/arduino/Print.d

.build_ano/pro/arduino/HID.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/HID.cpp
	@echo [93marduino/HID.cpp[0m
	@mkdir -p .build_ano/pro/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/HID.cpp
include .build_ano/pro/arduino/HID.d

.build_ano/pro/arduino/HardwareSerial0.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp
	@echo [93marduino/HardwareSerial0.cpp[0m
	@mkdir -p .build_ano/pro/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp
include .build_ano/pro/arduino/HardwareSerial0.d

.build_ano/pro/arduino/USBCore.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.cpp
	@echo [93marduino/USBCore.cpp[0m
	@mkdir -p .build_ano/pro/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.cpp
include .build_ano/pro/arduino/USBCore.d

.build_ano/pro/arduino/new.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp
	@echo [93marduino/new.cpp[0m
	@mkdir -p .build_ano/pro/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp
include .build_ano/pro/arduino/new.d

.build_ano/pro/arduino/HardwareSerial1.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp
	@echo [93marduino/HardwareSerial1.cpp[0m
	@mkdir -p .build_ano/pro/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp
include .build_ano/pro/arduino/HardwareSerial1.d

.build_ano/pro/arduino/Tone.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.cpp
	@echo [93marduino/Tone.cpp[0m
	@mkdir -p .build_ano/pro/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.cpp
include .build_ano/pro/arduino/Tone.d

.build_ano/pro/arduino/WString.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.cpp
	@echo [93marduino/WString.cpp[0m
	@mkdir -p .build_ano/pro/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.cpp
include .build_ano/pro/arduino/WString.d

.build_ano/pro/arduino/IPAddress.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.cpp
	@echo [93marduino/IPAddress.cpp[0m
	@mkdir -p .build_ano/pro/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.cpp
include .build_ano/pro/arduino/IPAddress.d

.build_ano/pro/arduino/HardwareSerial2.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp
	@echo [93marduino/HardwareSerial2.cpp[0m
	@mkdir -p .build_ano/pro/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp
include .build_ano/pro/arduino/HardwareSerial2.d

.build_ano/pro/arduino/CDC.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp
	@echo [93marduino/CDC.cpp[0m
	@mkdir -p .build_ano/pro/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp
include .build_ano/pro/arduino/CDC.d

.build_ano/pro/arduino/HardwareSerial3.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp
	@echo [93marduino/HardwareSerial3.cpp[0m
	@mkdir -p .build_ano/pro/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp
include .build_ano/pro/arduino/HardwareSerial3.d

.build_ano/pro/arduino/HardwareSerial.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp
	@echo [93marduino/HardwareSerial.cpp[0m
	@mkdir -p .build_ano/pro/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp
include .build_ano/pro/arduino/HardwareSerial.d

.build_ano/pro/arduino/abi.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.cpp
	@echo [93marduino/abi.cpp[0m
	@mkdir -p .build_ano/pro/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.cpp
include .build_ano/pro/arduino/abi.d

.build_ano/pro/arduino/main.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/main.cpp
	@echo [93marduino/main.cpp[0m
	@mkdir -p .build_ano/pro/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/main.cpp
include .build_ano/pro/arduino/main.d

.build_ano/pro/arduino/WMath.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.cpp
	@echo [93marduino/WMath.cpp[0m
	@mkdir -p .build_ano/pro/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.cpp
include .build_ano/pro/arduino/WMath.d

.build_ano/pro/arduino/Stream.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.cpp
	@echo [93marduino/Stream.cpp[0m
	@mkdir -p .build_ano/pro/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.cpp
include .build_ano/pro/arduino/Stream.d



.build_ano/pro/arduino/libarduino.a : .build_ano/pro/arduino/hooks.o .build_ano/pro/arduino/WInterrupts.o .build_ano/pro/arduino/wiring_shift.o .build_ano/pro/arduino/wiring_pulse.o .build_ano/pro/arduino/wiring_analog.o .build_ano/pro/arduino/wiring_digital.o .build_ano/pro/arduino/wiring.o .build_ano/pro/arduino/Print.o .build_ano/pro/arduino/HID.o .build_ano/pro/arduino/HardwareSerial0.o .build_ano/pro/arduino/USBCore.o .build_ano/pro/arduino/new.o .build_ano/pro/arduino/HardwareSerial1.o .build_ano/pro/arduino/Tone.o .build_ano/pro/arduino/WString.o .build_ano/pro/arduino/IPAddress.o .build_ano/pro/arduino/HardwareSerial2.o .build_ano/pro/arduino/CDC.o .build_ano/pro/arduino/HardwareSerial3.o .build_ano/pro/arduino/HardwareSerial.o .build_ano/pro/arduino/abi.o .build_ano/pro/arduino/main.o .build_ano/pro/arduino/WMath.o .build_ano/pro/arduino/Stream.o
	@echo [92mLinking libarduino.a[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^















.build_ano/pro/src/ant.o : .build_ano/pro/src/ant.cpp
	@echo [93msrc/ant.cpp[0m
	@mkdir -p .build_ano/pro/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/eightanaloginputs -Ilib/TimedAction -Ilib/RF22 -Ilib/RF22/doc -I/usr/share/arduino/hardware/arduino/avr/libraries/SPI -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions -iquote src  -o $@ -c .build_ano/pro/src/ant.cpp
include .build_ano/pro/src/ant.d







.build_ano/pro/firmware.elf : .build_ano/pro/src/ant.o .build_ano/pro/TimedAction/libTimedAction.a .build_ano/pro/RF22/libRF22.a .build_ano/pro/SPI/libSPI.a .build_ano/pro/arduino/libarduino.a
	@echo [92mLinking firmware.elf[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -Wl,-Os -Wl,--gc-sections -o $@ $^ -lm


.build_ano/pro/firmware.hex : .build_ano/pro/firmware.elf
	@echo [92mConverting to firmware.hex[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-objcopy -O ihex -R .eeprom $^ $@

include .build_ano/pro/src/dependencies.d .build_ano/pro/TimedAction/dependencies.d .build_ano/pro/arduino/dependencies.d .build_ano/pro/SPI/dependencies.d .build_ano/pro/RF22/dependencies.d

all : .build_ano/pro/firmware.hex
	@true

